{% set version = "1.7.1" %}

package:
  name: soupsieve
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: 009d8865916766f7f452880d08ff94ed4c5445011a3deaac67543b82bdb0b9ee

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - backports.functools_lru_cache  # [py<33]

test:
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup 

extra:
  recipe-maintainers:
    - jschueller
